package ru.stepanov.uocns.database.entities.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _TopologyReport was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TopologyReport extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> CONTENT = Property.create("content", String.class);
    public static final Property<Long> ID_TOPOLOGY = Property.create("idTopology", Long.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> PATH = Property.create("path", String.class);

    public void setContent(String content) {
        writeProperty("content", content);
    }
    public String getContent() {
        return (String)readProperty("content");
    }

    public void setIdTopology(long idTopology) {
        writeProperty("idTopology", idTopology);
    }
    public long getIdTopology() {
        Object value = readProperty("idTopology");
        return (value != null) ? (Long) value : 0;
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPath(String path) {
        writeProperty("path", path);
    }
    public String getPath() {
        return (String)readProperty("path");
    }

}
